language: python
python:
  # - "2.6"
  - "2.7"
  - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
install: 
    - pip install -r requirements.txt
    - npm install
# command to run tests
script: 
    - npm test
